<a href="https://colab.research.google.com/github/Carolalex1612/AI-Training/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CREATING ARRAY

In [1]:
import numpy as np

np.empty([2,2])

array([[1.76607698e-316, 0.00000000e+000],
       [4.94065646e-324, 6.59419063e-310]])

In [6]:
np.eye(2, dtype=int, k= 1)


array([[0, 1],
       [0, 0]])

In [8]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
x = np.array([[2, 3, 4],[3,4,5]])
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
y= np.zeros([2,3])
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
n1 = np.arange(10)
print(n1)

[0 1 2 3 4 5 6 7 8 9]
