<a href="https://colab.research.google.com/github/Carolalex1612/AI-Training/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CREATING ARRAY

In [ ]:
import numpy as np

np.empty([2,2])

array([[2.9135872e-316, 0.0000000e+000],
       [6.7167294e-310, 6.7167294e-310]])

In [ ]:
np.eye(2, dtype=int, k= 1)


array([[0, 1],
       [0, 0]])

In [ ]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
x = np.array([[2, 3, 4],[3,4,5],[2,3,4]])
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
y= np.zeros([2,3])
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
n1 = np.arange(10)
print(n1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
n2 = np.arange(-5,20,7 )
print(n2)

[-5  2  9 16]


In [ ]:
n3 = np.linspace(2,45, num=5, dtype=int)
print(n3)

[ 2 12 23 34 45]


In [ ]:
n4= np.full([2,3],89)
print(n4)

[[89 89 89]
 [89 89 89]]


ACCESSING ARRAY

In [ ]:
print(n3[-1])

45


In [ ]:
n5 = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
print(n5[1,:])
print(n5[2,3])
print(n5[:,2])

[2 3 4 5]
6
[3 4 5]


In [ ]:
n6 = np.array([[[1,2,3,4],[2,3,4,5],[3,4,5,6]],[[1,2,3,4],[2,3,4,5],[3,4,5,6]]])
print(n6)

[[[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]]


In [ ]:
n6[1,1,2] = 12
print(n6)

[[[ 1  2  3  4]
  [ 2  3  4  5]
  [ 3  4  5  6]]

 [[ 1  2  3  4]
  [ 2  3 12  5]
  [ 3  4  5  6]]]


SIZE AND SHAPE

In [ ]:
n6.ndim

3

In [ ]:
n6.shape

(2, 3, 4)

In [ ]:
n6.size

24

In [ ]:
n6.dtype

dtype('int64')

In [ ]:
# memory required to store each element
n6.itemsize

8

In [ ]:
# total memory to save the DS
n6.nbytes

192

SORTING

In [ ]:
sort_array = np.array([4,22,6,5,2,7,88,54,23,65,87,99])
np.sort(sort_array)

array([ 2,  4,  5,  6,  7, 22, 23, 54, 65, 87, 88, 99])

In [ ]:
sarr = np.array([[3,8,34],[56,1,9]])
np.sort(sarr)

array([[ 3,  8, 34],
       [ 1,  9, 56]])

In [ ]:
np.sort(sarr, axis=0)

array([[ 3,  1,  9],
       [56,  8, 34]])

RESHAPING AND ARRAY CONVERSATION

In [ ]:
n7= sort_array.reshape(3,4)
print(n7)

[[ 4 22  6  5]
 [ 2  7 88 54]
 [23 65 87 99]]


In [ ]:
#Join 2 arrays using concatenate
n8 = np.arange(4)
print(n8)
n9 = np.arange(5,9)
print(n9)
n10 = np.concatenate([n8,n9])
print(n10)

[0 1 2 3]
[5 6 7 8]
[0 1 2 3 5 6 7 8]


In [ ]:
n11 = sort_array[np.newaxis, :]
print(n11)
print(n11.shape)
n12 = sort_array[:, np.newaxis]
print(n12)
print(n12.shape)

[[ 4 22  6  5  2  7 88 54 23 65 87 99]]
(1, 12)
[[ 4]
 [22]
 [ 6]
 [ 5]
 [ 2]
 [ 7]
 [88]
 [54]
 [23]
 [65]
 [87]
 [99]]
(12, 1)


INDEXING ANS SLICING


In [ ]:
n10 = np.arange(10)
print(n10)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(n10[n10>5])
print(n10[(n10>3) & (n10<7)])

[6 7 8 9]
[4 5 6]


STACK AND SPLIT

In [ ]:
n11 = np.array([[3,5],[7,9]])
n12 = np.array([[1,4],[2,5]])
print(np.hstack((n11,n12)))
print(np.vstack((n11,n12)))


[[3 5 1 4]
 [7 9 2 5]]
[[3 5]
 [7 9]
 [1 4]
 [2 5]]


In [ ]:
n13= np.arange(20)
print(n13)
np.hsplit(n13,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

COPY

In [ ]:
n14= n13
n13[3]=100
print(n13)
print(n14)

[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [ ]:
n15= n14.copy()
n14[1]= 22
print(n14)
print(n15)



[  0  22   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[  0   2   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


MATH


In [ ]:
n15 = np.array([[1,3],[4,5]])
n16 = np.array([[2,4],[7,8]])
print(n15+n16)

[[ 3  7]
 [11 13]]
